version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace
    volumes:
      - .:/workspace
      - node-module-volume:/workspace/node_modules
    ports:
      - 3000:3000
      - 24678:24678
    stdin_open: true
    tty: true
    platform: linux/amd64
volumes:
  node-module-volume:
